name: story
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  get_it: ^9.1.1
  logger: ^2.5.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  go_router: ^17.0.0
  flutter_bloc: ^9.1.0
  retrofit_generator: ^10.2.0
  retrofit: ^4.4.2
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  flutter_gen_runner: ^5.10.0
  copy_with_extension: ^10.0.1
  copy_with_extension_gen: ^10.0.1
  equatable: ^2.0.7

  intl: ^0.20.2
  gap: ^3.0.1
  flutter_dotenv: ^6.0.0
  overlay_support: ^2.1.0
  loading_animation_widget: ^1.3.0
  toastification: ^3.0.2
  flex_color_scheme: ^8.4.0
  dio_curl_logger: ^1.2.0
  flutter_localization: ^0.3.3
  chewie: ^1.11.3
  video_player: ^2.9.5
  cached_network_image: ^3.4.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.1
  adaptive_dialog: ^2.4.1
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5

  bloc: any
  flutter_gen: ^5.12.0
  cupertino_native: ^0.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.14

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_gen:
  output: lib/core/gen/

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/
    - assets/images/
    - .env
